Update CI-Pipeline.yml
Signed-off-by: Jérémie P  <84284069+Jezzatator@users.noreply.github.com>

diff --git a/.github/workflows/CI-Pipeline.yml b/.github/workflows/CI-Pipeline.yml
--- a/.github/workflows/CI-Pipeline.yml
+++ b/.github/workflows/CI-Pipeline.yml
@@ -33,6 +33,8 @@ jobs:
 
       - name: Setup Tuist
         run: |
+          echo "PATH: $PATH"
+          which tuist || echo "tuist not found in PATH"
           tuist version
           tuist fetch
 
